build_ubuntu_16:
  stage: build
  image: trevorhanz/ubuntu:16.04
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_ubuntu_18:
  stage: build
  image: trevorhanz/ubuntu:18.04
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_web:
  stage: build
  image: trzeci/emscripten:1.39.4-ubuntu
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Modules/Emscripten.cmake ../
    - make

build_android:
  stage: build
  image: trevorhanz/android-ndk:r21d
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - >
       cmake 
       -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake 
       -DANDROID_ABI=x86 
       -DANDROID_NATIVE_API_LEVEL=28 
       ../
    - make
