build_ubuntu_16:
  stage: build
  image: trevorhanz/ubuntu:16.04
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_ubuntu_18:
  stage: build
  image: trevorhanz/ubuntu:18.04
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_centos_7:
  stage: build
  image: registry.gitlab.com/trevorhanz/graphicspipeline/centos7
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake3 ../
    - make

build_centos_8:
  stage: build
  image: registry.gitlab.com/trevorhanz/graphicspipeline/centos8
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_windows:
  stage: build
  image: trevorhanz/windows
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Modules/MinGW-W64.cmake ../
    - make

build_osx:
  stage: build
  image: liushuyu/osxcross
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - export OSXCROSS_HOST=x86_64-apple-darwin18
    - export OSXCROSS_TARGET=o64
    - export OSXCROSS_TARGET_DIR=/opt/osxcross/
    - export OSXCROSS_SDK=/opt/osxcross/SDK/MacOSX10.14.sdk/
    - cmake -DCMAKE_TOOLCHAIN_FILE=/opt/osxcross/toolchain.cmake ../
    - make

build_web:
  stage: build
  image: trevorhanz/emscripten:1.39.4
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Modules/Emscripten.cmake ../
    - make

build_android:
  stage: build
  image: trevorhanz/android-ndk:r21d
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - >
       cmake 
       -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake 
       -DANDROID_ABI=x86 
       -DANDROID_NATIVE_API_LEVEL=28 
       ../
    - make

pages:
  image: trevorhanz/emscripten:1.39.4
  tags:
    - docker
  script:
    - mkdir -p build/doxygen/
    - doxygen doxygen/Doxyfile
    - mv build/doxygen/html/ public
  artifacts:
    paths:
      - public
  only:
    - master
