stages:
  - build
  - analyze
  - deploy

build_ubuntu_16:
  stage: build
  image: $REGISTRY_ROOT/ubuntu:16
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_ubuntu_18:
  stage: build
  image: $REGISTRY_ROOT/ubuntu:18
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_ubuntu_20:
  stage: build
  image: $REGISTRY_ROOT/ubuntu:20
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_centos_7:
  stage: build
  image: $REGISTRY_ROOT/centos:7
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake3 ../
    - make

build_centos_8:
  stage: build
  image: $REGISTRY_ROOT/centos:8
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make

build_windows:
  stage: build
  image: $REGISTRY_ROOT/windows:mingw
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Modules/MinGW-W64.cmake ../
    - make

build_osx:
  stage: build
  image: $REGISTRY_ROOT/macos
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - export OSXCROSS_HOST=x86_64-apple-darwin18
    - export OSXCROSS_TARGET=o64
    - export OSXCROSS_TARGET_DIR=/opt/osxcross/
    - export OSXCROSS_SDK=/opt/osxcross/SDK/MacOSX10.14.sdk/
    - cmake -DCMAKE_TOOLCHAIN_FILE=/opt/osxcross/toolchain.cmake ../
    - make

build_web:
  stage: build
  image: $REGISTRY_ROOT/emscripten
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Modules/Emscripten.cmake ../
    - make

build_android:
  stage: build
  image: $REGISTRY_ROOT/android
  tags:
    - docker
  script:
    - mkdir build
    - cd build
    - >
       cmake 
       -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake 
       -DANDROID_ABI=x86 
       -DANDROID_NATIVE_API_LEVEL=28 
       ../
    - make

static_analysis:
  stage: analyze
  image: $REGISTRY_ROOT/ubuntu:20
  tags:
    - docker
  script:
    cppcheck --error-exitcode=1 ./
  allow_failure: true

pages:
  stage: deploy
  image: $REGISTRY_ROOT/emscripten
  tags:
    - docker
  script:
    - mkdir -p build/doxygen/
    - doxygen doxygen/Doxyfile
    - mv build/doxygen/html/ public
  artifacts:
    paths:
      - public
  only:
    - master
